services:
  cashflowjs:
    build:
      context: .
      dockerfile: Dockerfile.online
    container_name: cashflowjs-ru
    ports:
      - "127.0.0.1:12929:12930"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
